### ISSUE TITLE
Bioinformatics App Note latex template

### ISSUE THREAD

**Issue by jnovembre** [jhmarcus/ggv_paper#10]
We should use it - also need to deal with page / figure limits - this might be a problem and suggest a different journal target

**Comment by jhmarcus** [comment]
I downloaded the correct template. So can start to fill that in. Quick question would it be weird to post the note on bioarxiv with the bioinformatics template setup (the template has the journal logo etc etc)?

**Comment by jnovembre** [comment]
I agree about awkwardness.  My intuition is to get going in bioinformatics template so its ready to submit, but then revert to a more standard template for biorxiv posting.  Sound ok?

**Comment by jhmarcus** [comment]
works for me!

**Comment by jhmarcus** [comment]
Note here are instruction from bioinformatics 

http://www.oxfordjournals.org/our_journals/bioinformatics/for_authors/submission_online.html
