### ISSUE TITLE
Shortening and reconfiguring for Bioinformatics 

### ISSUE THREAD

**Issue by jnovembre** [jhmarcus/ggv_paper#12]

**Comment by jhmarcus** [comment]
Started to format the bioinformatics submission in 

```
ggv_paper/cabios-template/main.tex
ggv_paper/cabios-template/main.bib
ggv_paper/cabios-template/main.pdf
```

Definitely a bit of a challenge :) to shorten ... made a pass at it and will continue tomorrow. I was thinking to concisely mention the features (in about a paragraph or 2) that are each subsections now and reference the supplement for more information.

**Comment by jhmarcus** [comment]
keeping these here for reference ...

http://www.oxfordjournals.org/our_journals/bioinformatics/for_authors/submission_online.html
http://www.oxfordjournals.org/our_journals/bioinformatics/for_authors/general.html

**Comment by jhmarcus** [comment]
Made a prelim draft for the bioinformatics. Just need to proofed it and organzine the supplemental figures / text.
