### ISSUE TITLE
Citation for SQL / REST API framework

### ISSUE THREAD

**Issue by jnovembre** [jhmarcus/ggv_paper#5]

**Comment by jnovembre** [comment]
at line ~66 and at line ~106

**Comment by jhmarcus** [comment]
Having a hard time find the proper way to cite software or packages. It seems many papers don't.

**Comment by jnovembre** [comment]
Ideally there is some white paper or a web-page by the creator that can be cited; however, even a textbook or review paper can work (e.g. in the absence of a clear creator for SQL or REST API who deserves credit we could cite a classic SQL textbook or REST API text)

**Comment by jhmarcus** [comment]
cited grinberg2014flask for these
