### ISSUE TITLE
Proofread and correct bibliography entries

### ISSUE THREAD

**Issue by jnovembre** [jhmarcus/ggv_paper#7]

**Comment by jhmarcus** [comment]
I went through all the bibtex entries and made sure they have all the same fields, with the exception of a a few books. Was there anything else specifically to fix at that was messed?

**Comment by jnovembre** [comment]
Bibtex often induces capitalization errors.  I think a general proofread though is in order (because sometimes author names are garbled, etc).

**Comment by jhmarcus** [comment]
ah ok

**Comment by jhmarcus** [comment]
should be good to go! might take one more obsessive skim

**Comment by jnovembre** [comment]
I gave it a good pass through
