### ISSUE TITLE
TODO items from old README.md

### ISSUE THREAD

**Issue by jnovembre** [jhmarcus/ggv_paper#9]
- double check @patterson2006population citation
- double check @furchedata citation
- double check @wessel2013generic citation
- double check @meyer2012high citation
- cite svg icons for figure1
- phrasing issue - does a variant have a geographic distribution or allele i.e. variants don't have frequencies its alleles / genotypes do
- is interface features the right section header

**Comment by jhmarcus** [comment]
double check @patterson2006population citation [done]
double check @furchedata citation 
double check @wessel2013generic citation 
double check @meyer2012high citation [done]
cite svg icons for figure1 [done]
phrasing issue - does a variant have a geographic distribution or allele i.e. variants don't have frequencies its alleles / genotypes do [done]
is interface features the right section header [done]

**Comment by jhmarcus** [comment]
double check @furchedata citation 
double check @wessel2013generic citation 

last remaining to dos for citations. I actually want to ask you about these @jnovembre that what the double check was a reminder for

**Comment by jnovembre** [comment]
Furche et al appears to lack a date?

Wessel looks ok.

There are still capitalization issues in any references (e.g. NCBI = ncbi in Sherry et al).

**Comment by jnovembre** [comment]
I fixed Furche et al and fixed capitalization issues in titles and journal names.
